### ISSUE TITLE
Can't Paste Into Text Fields

### ISSUE THREAD

**Issue by Sixdd6** [mmatyas/pegasus-metadata-editor#2]
When creating a directory entry it is not possible to paste into the text box.

OS: Arch Linux, kernel 5.2
Release: pegasus-metadata-editor_c51cd32_x11-static.zip

If you need any other information I can provide it.

**Comment by mmatyas** [comment]
Oh you're right, I might have accidentally disabled the clipboard support when I prepared the releases. Will fix it, thanks!

**Comment by Sixdd6** [comment]
No problem, thanks for making a super handy tool :+1:

**Comment by mmatyas** [comment]
Haven't forgot about this, just run into some technical issues while building; hopefully this gets fixed about tomorrow.

**Comment by mmatyas** [comment]
Ok, this should work again now in the latest releases.
